---
params:
  nyTitle: "Sykehusnavn"
  nyDate: !r Sys.Date()
  nySubTitle: "Tidsperioden"
title: "`r params$nyTitle`"
date: "`r params$nyDate`"
subtitle: "`r params$nySubTitle`"
documentclass: book
site: bookdown::bookdown_site
header-includes:
- \usepackage{booktabs}
- \usepackage{longtable}
- \usepackage{array}
- \usepackage{multirow}
- \usepackage[table]{xcolor}
- \usepackage{wrapfig}
- \usepackage{float}
- \usepackage{colortbl}
- \usepackage{pdflscape}
- \usepackage{tabu}
- \usepackage{threeparttable}
- \usepackage{threeparttablex}
- \usepackage[normalem]{ulem}
- \usepackage{makecell}
- \usepackage[T1]{fontenc}
- \usepackage[utf8]{inputenc}
- \renewcommand{\figurename}{Figur:}

output:
  bookdown::gitbook:
    lib_dir: "ekstra"
    split_by: section
    download: ["pdf"]
  bookdown::pdf_document2:
    keep_tex: yes
    toc: no
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r test, eval=F, include=F }

inspak <- function(pkg){
  nypkg <- pkg[!(pkg %in% installed.packages()[, "Package"])]
  if (length(nypkg)) install.packages(nypkg, dependencies = TRUE, repos = "http://cran.rstudio.com")
  sapply(pkg, require, character.only = TRUE)
}

pkgs = c("data.table", "stringi", "validate", "ggplot2", "lubridate", "readxl", "sqldf", "huxtable")

inspak(pkgs)


## Setup
## -------
# source(file.path(kilde, "setup.R", fsep = "\\"))
## Hente data for årskontroll 2018
## --------------------------------
# dt2018 <- readRDS(file.path("../.."), "validert_arskontroll2018.rds")
dataSti <- "K:\\Sensitivt\\Forskning02\\Barnediabetesregisteret_2015-5739\\Barnediabetes og kvalitet\\Datafiler\\2018"
ars2018 <- readRDS(file.path(dataSti, "validert_arskontroll2018.rds", fsep = "\\"))

```



## Typer diabetes {-}

```{r r diabtype, echo=FALSE}
source("./analyse/type_diabetes.R")
```
Total pasienter med forskjellige typer diabetes er **`r antall.lokal`** pasienter, mens antall pasienter i hele landet som har tatt årskontroll i 2018 er **`r antall.nasj`** pasienter.


```{r diabetes, eval=F, echo=FALSE}

if (knitr::is_html_output()){
  kable(diab.lokal, format = "html") %>%
    kable_styling(bootstrap_options = c("striped", "hover")) %>%
    row_spec(3, bold = T, color = "black", background = "#c0c0c0")
}

## if (knitr::opts_knit$get('rmarkdown.pandoc.to') == "latex"){
##   kable(diab.nasj)
## }

if (knitr::is_latex_output()){
##   kable(diab.nasj, format = "latex", booktabs = T) %>%
##     kable_styling(latex_options = "striped")

  kable(diab.lokal, "latex", booktabs = T) %>%
    kable_styling(latex_options = "striped") %>%
    row_spec(3, bold = T, color = "black", background = "#c0c0c0")
  
    
}

```

```{r r huxtabdt, eval=T, echo=F}
library(huxtable)

hTB <- as_hux(diab.lokal, add_colnames = TRUE)
caption(hTB) <- "Antall pasienter med alle type diabetes"
bold(hTB)[1, ]  <- TRUE
bottom_border(hTB)[1, ] <- 1


if (knitr::is_html_output()){
  hTB
 
}

if (knitr::is_latex_output()){
 hTB
}

```


## Samtykke {-}

Antall samtykke

```{r data1}
data(mtcars)
car_ht <- as_hux(mtcars)
car_ht
```

