---
title: "BDR: Prevalens og insidens"
runtime: shiny
output:
  flexdashboard::flex_dashboard:
    orientation: row
    vertical_layout: fill
    includes:
      after_body: "busy.html"
---

```{r setup_manual, include=FALSE, eval=FALSE}
list.pkg <- c("flexdashboard", "shiny", "data.table", "dplyr", "plotly", "DT", "leaflet", "lubridate", "magrittr", "tmap", "mapview", "leafpop", "shinycssloaders")
new.packages <- list.pkg[!(list.pkg %in% installed.packages()[,"Package"])]
if(length(new.packages)) install.packages(new.packages, repos = "https://cloud.r-project.org/")
## reqopt <- function(x) require(x, quietly = TRUE)
sapply(list.pkg, require, character.only = TRUE)

```

```{r setup, include=FALSE}
library(flexdashboard)
library(shiny)
library(data.table)
library(dplyr)
library(leaflet)
library(magrittr)
library(tmap)
library(mapview)
library(leafpop)
library(DT)

pdf(NULL)
```





```{r load_data, include=FALSE}
## load data med HF
mapssb <- readRDS("SSBmedHFogKartID.rds")
dt2018 <- readRDS("DTannonHF.rds")
norgeMapFylke <- readRDS("NorgeMapFylkeID.Rds")
fylkeID <- readRDS("FylkeID.rds")


## omkode diabetes til T1D og Andre
dt2018[, diab12  :=  dbtype] %>%
  .[dbtype != 1, diab12 := 2]


## function


preCount <- function(x, y){
  
  ## x = DB data
  ## y = fylke data
  preDT <- x[y, on = "fylkeid"]

  preDT[, ins10 := N / i.N * 10000] %>%
    .[, ins := N / i.N * 100]

  ## columns for fylkeid og mapID
  utCol <- grep("id$", names(preDT), ignore.case = TRUE)

  tabCol <- names(preDT)[-utCol]
  tabName <- c("Case", "Populasjon", "pr.10000", "pr.100")
  setnames(preDT, tabCol, tabName)

  preDT[, (tabName) := lapply(.SD, function(x1) round(x1, digits = 1)),
    .SDcols = tabName]

  preDT[is.na(mapID), mapID := 50] #for Trøndelag
  return(preDT)
}


```




```{r reaktiv}
## populasjon
pop_ut <- reactive({

  dt <- mapssb[kjonn %in% input$valg_kjonn, ] %>%
      .[age >= as.integer(input$valg_age[1]) & age <= as.integer(input$valg_age[2]), ]

    popDT <- dt[, .(N = sum(N)), keyby = .(fylkeid, mapID)]

  return(popDT)
    
})


## diabetes pop
diab_ut <- reactive({
  
  if (input$valg_diab != 3){
    dt1 <- dt2018[diab12 == input$valg_diab, ]
  } else {
    dt1 <- dt2018
  }

  diabData = dt1[kjonn %in% input$valg_kjonn, ] %>%
    .[age >= input$valg_age[1] & age <= input$valg_age[2], ]

  return(diabData)
  
})



## kart
preData_ut <- reactive({
  
  if (input$valg_inspre == 1) {
    preNorge <- pop_ut()[, .(N = sum(N, na.rm = TRUE)), keyby = .(fylkeid, mapID)][N != 0, ][]
    preDiab <- diab_ut()[, .N, keyby = .(fylkeid)]
    utDataKart <- preCount(preDiab, preNorge)

  } else {

    #pasienter
    insPas = diab_ut()[valg == 2, .(n = .N), keyby = .(fylkeid)]
    sykPas = diab_ut()[valg == 1, .(ut = .N), keyby = .(fylkeid)]
    insDT = merge(insPas, sykPas, by = "fylkeid", all = TRUE)

    #norges populasjon
    insPop = pop_ut()[, .(pop = sum(N, na.rm = T)), keyby = .(fylkeid, mapID)]
    
    insLand = merge(insDT, insPop, by.x = "fylkeid", by.y = "fylkeid", all.y = TRUE)
    
    tabIns = insLand[pop != 0, ]
    tabIns[is.na(mapID), mapID := 50]
    tabIns[, denom := pop - ut]
    tabIns[, `:=`(ins = round(n / denom * 100, digits = 3), ins10 = round(n / denom * 10000, digits = 2)), by = fylkeid]

    tabName <- c("Case", "Populasjon", "pr.10000", "pr.100")
    setnames(tabIns, c("n", "denom", "ins10", "ins"), tabName)
    utDataKart = tabIns
    
  }

  return(utDataKart)
  
})



## landet
pre_ut <- reactive({
  
  n <- preData_ut()[, sum(Case, na.rm = TRUE)]
  N <- preData_ut()[, sum(Populasjon, na.rm = TRUE)]

  pre1 <- round(n / N * 100, digits = 2)
  pre10 <- round(n / N * 10000, digits = 0)

  preTall = c(pre1, pre10)


  return(preTall)
})


## Kart og data
kartDT_ut <- eventReactive(input$go, {
  req(input$valg_inspre)
  kartUT = norgeMapFylke %>% left_join(preData_ut(), by = "mapID")

  return(kartUT)
})

```





Sidebar {.sidebar}
===================================

```{r input1}
selectInput("valg_data",
            "Valg nivå: ",
            choices = list(
              "HF" = 1,
              "Fylke" = 2),
            selected =  2)

```




```{r inspre}



selectInput("valg_inspre",
            "Valg data:",
            choices = list("Prevalens" = 1,
                           "Insidens" = 2),
            selected = 1)
```



```{r typeDiab}
selectInput("valg_diab",
            "Valg diabetes type:",
            choices = list("Type I" = 1,
                           "Annen" = 2,
                           "Alle" = 3),
            selected = 1)

sliderInput("valg_age",
           "Alder:",
           min = 0L,
           max = 14L,
           value = c(0L, 14L),
           step = 1)


checkboxGroupInput("valg_kjonn",
                   "Kjønn:", 
                   choices = list("Gutter" = 1,
                                  "Jenter" = 2
                                  ),
                   selected = c(1, 2),
                   inline = TRUE)

## submitButton("Oppdatere", icon("refresh"))
actionButton("go", " Oppdatere kart", icon("refresh"),
  style="color: #fff; background-color: #447af7; border-color: #2e6da4")

```

<sub> Klikk på kartet for mer informasjon</sub>


[Tilbake til BDR hjemmeside](https://bdreg.github.io)



Pr. 100 personer (%)
===================================


Row
-----------------------------------

### Antall pasienter {.no-title}


```{r}
renderValueBox({
  
  npop = preData_ut()[, sum(Case, na.rm = TRUE)]

    
  kjonnLg = length(input$valg_kjonn)

  if (kjonnLg == 2) {
    kjonn = " "
  } else {
    kjonn = switch(as.character(input$valg_kjonn),
      "1" = " : Gutter",
      "2" = " : Jenter")
  }
  
  barnTxt <- paste0("Antall pasienter: ", input$valg_age[1], " - ", input$valg_age[2], " år", kjonn)
  valueBox(barnTxt, value = npop, icon = "fa-child")
  
})
```

### Totalt populasjon {.no-title}

```{r}
renderValueBox({

  antallPas = preData_ut()[, sum(Populasjon, na.rm = TRUE)]
  
  barnTxt <- paste0("Total populasjon: ", input$valg_age[1], " - ", input$valg_age[2], " år")
  valueBox(barnTxt, value = antallPas, icon = "fa-user-friends")
})


```

### Prevalens eller Insidens {.no-title}

```{r}
renderValueBox({
  txtInn <- ifelse(input$valg_inspre == 1, "Landet Prevalens", "Landet Insidens")
  valueBox(paste0(txtInn, " (%)"), value = pre_ut()[1],  icon = "fa-pie-chart",color="warning")
})
## valueBox("-2°C", icon = "fa-life-ring",color="rgb(26,110,204)")
```



Row 
---------------------------------------------------

### 

```{r}

## mapData <- eventReactive(input$go, {

##   kartDT <- norgeMapFylke %>% left_join(preData_ut(), by = "mapID")

## })



output[["kartDT"]] <- renderLeaflet({

  
  valgTxt = ifelse(input$valg_inspre == 1, "Prevalens", "Insidens")
  txtLeg <- paste0(valgTxt, " (", input$valg_age[1], " - ", input$valg_age[2], " år)")
  
  ## kartDT <- norgeMapFylke %>% left_join(preData_ut(), by = "mapID")
  ## mapview(kartDT, zcol = "pr100")@map
  ## kartDT <- mapData()

  
  mapview(kartDT_ut(), zcol = "pr.100",
    popup = leafpop::popupTable(kartDT_ut(), zcol = c("region", "pr.100", "Case", "Populasjon"),
      feature.id = FALSE, row.numbers = FALSE), layer.name = txtLeg)@map
      
    ## mapview(kartDT, zcol = "pr.100", popup = leafpop::popupTable(kartDT, zcol = 1:2, feature.id = FALSE, row.number = FALSE))@map
  
})

## leafletOutput("kartDT") %>% shinycssloaders::withSpinner()
leafletOutput("kartDT")

```




Pr. 10,000 personer
===================================



Row
-----------------------------------

### Antall pasienter {.no-title}


```{r}

renderValueBox({
  
  npop = preData_ut()[, sum(Case, na.rm = TRUE)]

      
  kjonnLg = length(input$valg_kjonn)

  if (kjonnLg == 2) {
    kjonn = " "
  } else {
    kjonn = switch(as.character(input$valg_kjonn),
      "1" = " : Gutter",
      "2" = " : Jenter")
  }
  
  barnTxt <- paste0("Antall pasienter: ", input$valg_age[1], " - ", input$valg_age[2], " år", kjonn)
  valueBox(barnTxt, value = npop, icon = "fa-child")
  
})

```

### Totalt populasjon

```{r}

renderValueBox({

  antallPas = preData_ut()[, sum(Populasjon, na.rm = TRUE)]
  
  barnTxt <- paste0("Total populasjon: ", input$valg_age[1], " - ", input$valg_age[2], " år")
  valueBox(barnTxt, value = antallPas, icon = "fa-user-friends")
})


```

### Prevalens eller Insidens {.no-title}

```{r}
renderValueBox({
  txtInn <- ifelse(input$valg_inspre == 1, "Landet Prevalens", "Landet Insidens")
  valueBox(paste0(txtInn, " pr. 10,000 personer"), value = pre_ut()[2],  icon = "fa-pie-chart",color="warning")
})
## valueBox("-2°C", icon = "fa-life-ring",color="rgb(26,110,204)")
```



Row 
---------------------------------------------------

### 

```{r}

## mapData <- eventReactive(input$go, {
##   kartDT <- norgeMapFylke %>% left_join(preData_ut(), by = "mapID")
## })

output[["kartDT2"]] <- renderLeaflet({

  
  valgTxt = ifelse(input$valg_inspre == 1, "Prevalens", "Insidens")
  txtLeg <- paste0(valgTxt, " (", input$valg_age[1], " - ", input$valg_age[2], " år)")

  ## kartDT <- norgeMapFylke %>% left_join(preData_ut(), by = "mapID")
  ## kartDT <- norgeMapFylke %>% left_join(preData_ut(), by = "mapID")
  
  ## mapview(kartDT, zcol = "pr100")@map
  ## kartDT <- mapData()
  mapview(kartDT_ut(), zcol = "pr.10000",
    popup = leafpop::popupTable(kartDT_ut(), zcol = c("region", "pr.10000", "Case", "Populasjon"),
      feature.id = FALSE, row.numbers = FALSE), layer.name = txtLeg)@map
  
    ## mapview(kartDT, zcol = "pr.100", popup = leafpop::popupTable(kartDT, zcol = 1:2, feature.id = FALSE, row.number = FALSE))@map
  
})

## leafletOutput("kartDT2") %>% shinycssloaders::withSpinner()
leafletOutput("kartDT2")

```


Tabell
===================================

<h3>Tabell for basis tall</h3>

Row {data-height=650}
-----------------------------------

```{r}

options(DT.options = list(pageLength = 10))
DT::renderDT({
  utTabell <- merge(preData_ut(), fylkeID, by = "mapID")
  utTabell[, fylkeid := NULL] %>%
    .[, mapID := NULL]

  if(input$valg_inspre == 2){
    setnames(utTabell, c("Case", "ut", "pop", "Populasjon"), c("Ny pas.", "Allede med diab.", "Populasjon", "'Friske' pop."))
  }

  return(utTabell)
})

```


Informasjon
===================================

<h3> **Data** </h3> 

Datagrunnlagt er for barn mellom 0 til 14 år som er registeret i BDR.











